a=int(input('enter a number'))
b=int(input('enter another number'))
print('sum is: ', a+b)
print('diff is: ', a-b)
print('div is: ', a/b)
print('float div is: ', a//b)
print('mod is: ', a%b)
print('pow is: ', a**b)
print('mul is: ', a*b)